version: "3.8"

name: "gomoku-royale"

services:
  webapp:
    build: ./code/js
    restart: on-failure
    ports:
      - "80:8080"
    depends_on:
      - entry
    networks:
      - gomoku-royale

  entry:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apiapp
    networks:
      - gomoku-royale

  apiapp:
    build: ./code/jvm
    restart: on-failure
    environment:
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      JDBI_DATABASE_URL: jdbc:postgresql://datastore:5432/daw?user=postgres&password=postgres
      JDBI_TEST_DATABASE_URL: jdbc:postgresql://datastore:5432/dawtest?user=postgres&password=postgres
    depends_on:
      datastore:
        condition: service_healthy
    networks:
      - gomoku-royale

  datastore:
    build: ./code/jvm/src/sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: daw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - gomoku-royale
    ports:
      - "5433:5432"

volumes:
  db:

networks:
  gomoku-royale: {}